<a href="https://colab.research.google.com/github/redsoil/Df_Ordering/blob/main/Df_cleaning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import files

In [ ]:
uploaded = files.upload()

Saving df.csv to df (1).csv

In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv('df.csv')

In [ ]:
df

,Job Title,Salary Estimate,Rating,Company Name,Location,Size,Founded,Type of ownership,Industry,Sector,Revenue
0,Senior Data Scientist,$111K-$181K (Glassdoor est.),3.5,Hopper\n3.5,"New York, NY",501 to 1000 employees,2007,Company - Private,Travel Agencies,Travel & Tourism,Unknown / Non-Applicable
1,"Data Scientist, Product Analytics",$111K-$181K (Glassdoor est.),4.5,Noom US\n4.5,"New York, NY",1001 to 5000 employees,2008,Company - Private,"Health, Beauty, & Fitness",Consumer Services,Unknown / Non-Applicable
2,Data Science Manager,$111K-$181K (Glassdoor est.),-1.0,Decode_M,"New York, NY",1 to 50 employees,-1,Unknown,-1,-1,Unknown / Non-Applicable
3,Data Analyst,$111K-$181K (Glassdoor est.),3.4,Sapphire Digital\n3.4,"Lyndhurst, NJ",201 to 500 employees,2019,Company - Private,Internet,Information Technology,Unknown / Non-Applicable
4,"Director, Data Science",$111K-$181K (Glassdoor est.),3.4,United Entertainment Group\n3.4,"New York, NY",51 to 200 employees,2007,Company - Private,Advertising & Marketing,Business Services,Unknown / Non-Applicable
...,...,...,...,...,...,...,...,...,...,...,...
5887,Manufacturing Data Analyst Engineer,$42K - $76K (Glassdoor est.),3.6,Hose Master\n3.6,"Euclid, OH",201 to 500 Employees,1982,Company - Private,Electrical & Electronic Manufacturing,Manufacturing,Unknown / Non-Applicable
5888,Data Scientist,-1,4.9,Bluetree Network\n4.9,"Madison, WI",-1,-1,-1,-1,-1,-1
5889,Supply Chain Consultant - Data Scientist,-1,4.0,"Kimberly-Clark Corporation, LLC\n4.0","Neenah, WI",10000+ Employees,1872,Company - Public,Consumer Products Manufacturing,Manufacturing,$10+ billion (USD)
5890,Data Science Engineer,-1,4.0,AE Business Solutions\n4.0,"Madison, WI",51 to 200 Employees,1949,Company - Private,Computer Hardware & Software,Information Technology,$25 to $50 million (USD)
5891,Data Scientist/ Full Stack Developer,$65 - $72 Per Hour,3.7,Epitec\n3.7,"Wisconsin, WI",1001 to 5000 Employees,1978,Company - Private,Staffing & Outsourcing,Business Services,$100 to $500 million (USD)

In [ ]:
def dollar_remover(a):

  a = a.replace('$', '')
  return a

In [ ]:
df['Salary Estimate'] = df['Salary Estimate'].apply(dollar_remover)

In [ ]:
df

,Job Title,Salary Estimate,Rating,Company Name,Location,Size,Founded,Type of ownership,Industry,Sector,Revenue
0,Senior Data Scientist,111K-181K (Glassdoor est.),3.5,Hopper\n3.5,"New York, NY",501 to 1000 employees,2007,Company - Private,Travel Agencies,Travel & Tourism,Unknown / Non-Applicable
1,"Data Scientist, Product Analytics",111K-181K (Glassdoor est.),4.5,Noom US\n4.5,"New York, NY",1001 to 5000 employees,2008,Company - Private,"Health, Beauty, & Fitness",Consumer Services,Unknown / Non-Applicable
2,Data Science Manager,111K-181K (Glassdoor est.),-1.0,Decode_M,"New York, NY",1 to 50 employees,-1,Unknown,-1,-1,Unknown / Non-Applicable
3,Data Analyst,111K-181K (Glassdoor est.),3.4,Sapphire Digital\n3.4,"Lyndhurst, NJ",201 to 500 employees,2019,Company - Private,Internet,Information Technology,Unknown / Non-Applicable
4,"Director, Data Science",111K-181K (Glassdoor est.),3.4,United Entertainment Group\n3.4,"New York, NY",51 to 200 employees,2007,Company - Private,Advertising & Marketing,Business Services,Unknown / Non-Applicable
...,...,...,...,...,...,...,...,...,...,...,...
5887,Manufacturing Data Analyst Engineer,42K - 76K (Glassdoor est.),3.6,Hose Master\n3.6,"Euclid, OH",201 to 500 Employees,1982,Company - Private,Electrical & Electronic Manufacturing,Manufacturing,Unknown / Non-Applicable
5888,Data Scientist,-1,4.9,Bluetree Network\n4.9,"Madison, WI",-1,-1,-1,-1,-1,-1
5889,Supply Chain Consultant - Data Scientist,-1,4.0,"Kimberly-Clark Corporation, LLC\n4.0","Neenah, WI",10000+ Employees,1872,Company - Public,Consumer Products Manufacturing,Manufacturing,$10+ billion (USD)
5890,Data Science Engineer,-1,4.0,AE Business Solutions\n4.0,"Madison, WI",51 to 200 Employees,1949,Company - Private,Computer Hardware & Software,Information Technology,$25 to $50 million (USD)
5891,Data Scientist/ Full Stack Developer,65 - 72 Per Hour,3.7,Epitec\n3.7,"Wisconsin, WI",1001 to 5000 Employees,1978,Company - Private,Staffing & Outsourcing,Business Services,$100 to $500 million (USD)

In [ ]:
def k_remover(b):

  b = b.replace('K', '')
  return b

In [ ]:
df['Salary Estimate'] = df['Salary Estimate'].apply(k_remover)

In [ ]:
df

,Job Title,Salary Estimate,Rating,Company Name,Location,Size,Founded,Type of ownership,Industry,Sector,Revenue
0,Senior Data Scientist,111-181 (Glassdoor est.),3.5,Hopper\n3.5,"New York, NY",501 to 1000 employees,2007,Company - Private,Travel Agencies,Travel & Tourism,Unknown / Non-Applicable
1,"Data Scientist, Product Analytics",111-181 (Glassdoor est.),4.5,Noom US\n4.5,"New York, NY",1001 to 5000 employees,2008,Company - Private,"Health, Beauty, & Fitness",Consumer Services,Unknown / Non-Applicable
2,Data Science Manager,111-181 (Glassdoor est.),-1.0,Decode_M,"New York, NY",1 to 50 employees,-1,Unknown,-1,-1,Unknown / Non-Applicable
3,Data Analyst,111-181 (Glassdoor est.),3.4,Sapphire Digital\n3.4,"Lyndhurst, NJ",201 to 500 employees,2019,Company - Private,Internet,Information Technology,Unknown / Non-Applicable
4,"Director, Data Science",111-181 (Glassdoor est.),3.4,United Entertainment Group\n3.4,"New York, NY",51 to 200 employees,2007,Company - Private,Advertising & Marketing,Business Services,Unknown / Non-Applicable
...,...,...,...,...,...,...,...,...,...,...,...
5887,Manufacturing Data Analyst Engineer,42 - 76 (Glassdoor est.),3.6,Hose Master\n3.6,"Euclid, OH",201 to 500 Employees,1982,Company - Private,Electrical & Electronic Manufacturing,Manufacturing,Unknown / Non-Applicable
5888,Data Scientist,-1,4.9,Bluetree Network\n4.9,"Madison, WI",-1,-1,-1,-1,-1,-1
5889,Supply Chain Consultant - Data Scientist,-1,4.0,"Kimberly-Clark Corporation, LLC\n4.0","Neenah, WI",10000+ Employees,1872,Company - Public,Consumer Products Manufacturing,Manufacturing,$10+ billion (USD)
5890,Data Science Engineer,-1,4.0,AE Business Solutions\n4.0,"Madison, WI",51 to 200 Employees,1949,Company - Private,Computer Hardware & Software,Information Technology,$25 to $50 million (USD)
5891,Data Scientist/ Full Stack Developer,65 - 72 Per Hour,3.7,Epitec\n3.7,"Wisconsin, WI",1001 to 5000 Employees,1978,Company - Private,Staffing & Outsourcing,Business Services,$100 to $500 million (USD)

In [ ]:
df = df[df['Salary Estimate'] != '-1']

In [ ]:
df

,Job Title,Salary Estimate,Rating,Company Name,Location,Size,Founded,Type of ownership,Industry,Sector,Revenue
0,Senior Data Scientist,111-181 (Glassdoor est.),3.5,Hopper\n3.5,"New York, NY",501 to 1000 employees,2007,Company - Private,Travel Agencies,Travel & Tourism,Unknown / Non-Applicable
1,"Data Scientist, Product Analytics",111-181 (Glassdoor est.),4.5,Noom US\n4.5,"New York, NY",1001 to 5000 employees,2008,Company - Private,"Health, Beauty, & Fitness",Consumer Services,Unknown / Non-Applicable
2,Data Science Manager,111-181 (Glassdoor est.),-1.0,Decode_M,"New York, NY",1 to 50 employees,-1,Unknown,-1,-1,Unknown / Non-Applicable
3,Data Analyst,111-181 (Glassdoor est.),3.4,Sapphire Digital\n3.4,"Lyndhurst, NJ",201 to 500 employees,2019,Company - Private,Internet,Information Technology,Unknown / Non-Applicable
4,"Director, Data Science",111-181 (Glassdoor est.),3.4,United Entertainment Group\n3.4,"New York, NY",51 to 200 employees,2007,Company - Private,Advertising & Marketing,Business Services,Unknown / Non-Applicable
...,...,...,...,...,...,...,...,...,...,...,...
5882,Supervisory Research Health Scientist,47 - 89 (Glassdoor est.),4.2,Centers for Disease Control and Prevention\n4.2,"Cincinnati, OH",10000+ Employees,1946,Government,Federal Agencies,Government,Unknown / Non-Applicable
5883,Senior SAS Programmer (Scientist),66 - 113 (Glassdoor est.),4.0,Certara\n4.0,"Cincinnati, OH",501 to 1000 Employees,2008,Company - Public,Biotech & Pharmaceuticals,Biotech & Pharmaceuticals,Unknown / Non-Applicable
5886,Senior Data Analyst - Product Analytics (open ...,67 - 111 (Glassdoor est.),4.0,New Relic\n4.0,"Cincinnati, OH",1001 to 5000 Employees,2008,Company - Public,Computer Hardware & Software,Information Technology,$100 to $500 million (USD)
5887,Manufacturing Data Analyst Engineer,42 - 76 (Glassdoor est.),3.6,Hose Master\n3.6,"Euclid, OH",201 to 500 Employees,1982,Company - Private,Electrical & Electronic Manufacturing,Manufacturing,Unknown / Non-Applicable
5891,Data Scientist/ Full Stack Developer,65 - 72 Per Hour,3.7,Epitec\n3.7,"Wisconsin, WI",1001 to 5000 Employees,1978,Company - Private,Staffing & Outsourcing,Business Services,$100 to $500 million (USD)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 5526 entries, 0 to 5891
Data columns (total 11 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Job Title          5526 non-null   object
 1   Salary Estimate    5526 non-null   object
 2   Rating             5526 non-null   float64
 3   Company Name       5526 non-null   object
 4   Location           5526 non-null   object
 5   Size               5526 non-null   object
 6   Founded            5526 non-null   object
 7   Type of ownership  5526 non-null   object
 8   Industry           5526 non-null   object
 9   Sector             5526 non-null   object
 10  Revenue            5526 non-null   object
dtypes: float64(1), object(10)
memory usage: 518.1+ KB

In [37]:
df[df['Salary Estimate'].str.contains('Per Hour')]

,Job Title,Salary Estimate,Rating,Company Name,Location,Size,Founded,Type of ownership,Industry,Sector,Revenue
685,"Clinical Laboratory Scientist, Per Diem",34-53 Per Hour(Glassdoor est.),3.8,UC Davis Medical Center\n3.8,"Los Angeles, CA",10000+ employees,-1,Nonprofit Organization,Health Care Services & Hospitals,Health Care,$2 to $5 billion (USD)
686,Sr. Data Analyst,34-53 Per Hour(Glassdoor est.),2.8,SAG-AFTRA Health Plan and SAG-Producers Pensio...,"Burbank, CA",Unknown,-1,Company - Private,-1,-1,Unknown / Non-Applicable
687,"Lead Data Science Instructor, Data Scientist",34-53 Per Hour(Glassdoor est.),-1.0,Galvanize Inc.,"Los Angeles, CA",51 to 200 employees,-1,Company - Private,Construction,"Construction, Repair & Maintenance",Unknown / Non-Applicable
688,"Clinical Laboratory Scientist (Per Diem, Varia...",34-53 Per Hour(Glassdoor est.),3.0,AHMC Healthcare\n3.0,"Monterey Park, CA",5001 to 10000 employees,1998,Company - Private,Health Care Services & Hospitals,Health Care,$1 to $2 billion (USD)
689,Data Engineer,34-53 Per Hour(Glassdoor est.),-1.0,BlackLine Systems,"Woodland Hills, CA",1 to 50 employees,-1,Unknown,-1,-1,Unknown / Non-Applicable
690,Clinical Laboratory Scientist - Generalist,34-53 Per Hour(Glassdoor est.),3.8,LetsGetChecked\n3.8,"Monrovia, CA",51 to 200 employees,2015,Company - Private,Health Care Services & Hospitals,Health Care,Unknown / Non-Applicable
691,"Clinical Laboratory Scientist , Med Tech",34-53 Per Hour(Glassdoor est.),3.4,Covance\n3.4,"Los Angeles, CA",10000+ employees,1996,Company - Public,Biotech & Pharmaceuticals,Biotech & Pharmaceuticals,$10 to $25 million (USD)
1295,Stafford Data Science Tutor Jobs,10-26 Per Hour(Glassdoor est.),4.2,Varsity Tutors\n4.2,"Stafford, TX",201 to 500 employees,2007,Company - Private,Internet,Information Technology,Unknown / Non-Applicable
1296,Spring Data Science Tutor Jobs,10-26 Per Hour(Glassdoor est.),4.2,Varsity Tutors\n4.2,"Spring, TX",201 to 500 employees,2007,Company - Private,Internet,Information Technology,Unknown / Non-Applicable
1297,Sugar Land Data Science Tutor Jobs,10-26 Per Hour(Glassdoor est.),4.2,Varsity Tutors\n4.2,"Sugar Land, TX",201 to 500 employees,2007,Company - Private,Internet,Information Technology,Unknown / Non-Applicable
2124,Laboratory Scientist II,17-27 Per Hour(Glassdoor est.),3.7,University Health System\n3.7,"San Antonio, TX",1001 to 5000 employees,1955,Nonprofit Organization,Health Care Services & Hospitals,Health Care,$100 to $500 million (USD)
2125,Data Engineer - Top Secret w/ SCI Eligibility,17-27 Per Hour(Glassdoor est.),4.0,LMI\n4.0,"San Antonio, TX",1001 to 5000 employees,1961,Nonprofit Organization,Consulting,Business Services,$100 to $500 million (USD)
2126,Biological Scientist,17-27 Per Hour(Glassdoor est.),4.2,U.S. Air Force\n4.2,"Lackland AFB, TX",10000+ employees,1947,Government,Federal Agencies,Government,$10+ billion (USD)
2127,TECHNICAL DATA ANALYST,17-27 Per Hour(Glassdoor est.),3.8,Spectrum Comm\n3.8,"Lackland AFB, TX",51 to 200 employees,1999,Company - Private,Aerospace & Defense,Aerospace & Defense,$25 to $50 million (USD)
2128,Environmental Scientist/Engineer,17-27 Per Hour(Glassdoor est.),4.0,"BB&E, Inc.\n4.0","San Antonio, TX",10000+ employees,-1,Company - Public,Banks & Credit Unions,Finance,$10+ billion (USD)
2129,Data Analyst with Security Clearance,17-27 Per Hour(Glassdoor est.),3.3,CDO Technologies Inc\n3.3,"San Antonio, TX",201 to 500 employees,1995,Company - Private,Computer Hardware & Software,Information Technology,$50 to $100 million (USD)
2130,"Associate Scientist, Process Development & Man...",17-27 Per Hour(Glassdoor est.),2.2,BioBridge Global\n2.2,"San Antonio, TX",501 to 1000 employees,2013,Nonprofit Organization,Biotech & Pharmaceuticals,Biotech & Pharmaceuticals,$1 to $5 million (USD)
2131,"Configuration Data Analyst, San Antonio, TX, U...",17-27 Per Hour(Glassdoor est.),-1.0,Cherokee Federal,"Fort Sam Houston, TX",1 to 50 employees,-1,Nonprofit Organization,Banks & Credit Unions,Finance,Unknown / Non-Applicable
2132,Research Scientist III,17-27 Per Hour(Glassdoor est.),3.5,General Dynamics Information Technology\n3.5,"Fort Sam Houston, TX",10000+ employees,1996,Subsidiary or Business Segment,IT Services,Information Technology,$10+ billion (USD)
2133,Senior Data Engineer,17-27 Per Hour(Glassdoor est.),-1.0,KCI Licensing,"San Antonio, TX",1001 to 5000 employees,-1,Company - Private,-1,-1,Unknown / Non-Applicable
2134,Lead of Cybersecurity Data Protection & Analytics,17-27 Per Hour(Glassdoor est.),3.6,Humana\n3.6,"San Antonio, TX",10000+ employees,1961,Company - Public,Insurance Carriers,Insurance,$10+ billion (USD)
3986,"Clinical Laboratory Scientist, Full Time, Even...",25 - 41 Per Hour(Glassdoor est.),3.6,Adventist Health\n3.6,"Lodi, CA",10000+ Employees,1973,Nonprofit Organization,Health Care Services & Hospitals,Health Care,Unknown / Non-Applicable
4034,Clinical Lab Scientist,11 - 19 Per Hour(Glassdoor est.),3.1,AG Globe Services\n3.1,"Fresno, CA",51 to 200 Employees,2015,Company - Private,Staffing & Outsourcing,Business Services,Unknown / Non-Applicable
5369,"Senior Clinical Scientist/Director, Clinical S...",53 - 90 Per Hour(Glassdoor est.),3.7,"Celldex Therapeutics, Inc.\n3.7","Hampton, NJ",-1,-1,-1,-1,-1,-1
5618,Medical Lab Scientist (MLS) Mercy Health St. E...,17 - 24 Per Hour(Glassdoor est.),3.7,Mercy Health\n3.7,"Youngstown, OH",10000+ Employees,1973,Hospital,Health Care Services & Hospitals,Health Care,$5 to $10 billion (USD)
5891,Data Scientist/ Full Stack Developer,65 - 72 Per Hour,3.7,Epitec\n3.7,"Wisconsin, WI",1001 to 5000 Employees,1978,Company - Private,Staffing & Outsourcing,Business Services,$100 to $500 million (USD)

In [38]:
df[~df['Salary Estimate'].str.contains('Per Hour')]

,Job Title,Salary Estimate,Rating,Company Name,Location,Size,Founded,Type of ownership,Industry,Sector,Revenue
0,Senior Data Scientist,111-181 (Glassdoor est.),3.5,Hopper\n3.5,"New York, NY",501 to 1000 employees,2007,Company - Private,Travel Agencies,Travel & Tourism,Unknown / Non-Applicable
1,"Data Scientist, Product Analytics",111-181 (Glassdoor est.),4.5,Noom US\n4.5,"New York, NY",1001 to 5000 employees,2008,Company - Private,"Health, Beauty, & Fitness",Consumer Services,Unknown / Non-Applicable
2,Data Science Manager,111-181 (Glassdoor est.),-1.0,Decode_M,"New York, NY",1 to 50 employees,-1,Unknown,-1,-1,Unknown / Non-Applicable
3,Data Analyst,111-181 (Glassdoor est.),3.4,Sapphire Digital\n3.4,"Lyndhurst, NJ",201 to 500 employees,2019,Company - Private,Internet,Information Technology,Unknown / Non-Applicable
4,"Director, Data Science",111-181 (Glassdoor est.),3.4,United Entertainment Group\n3.4,"New York, NY",51 to 200 employees,2007,Company - Private,Advertising & Marketing,Business Services,Unknown / Non-Applicable
...,...,...,...,...,...,...,...,...,...,...,...
5881,Information Scientist,38 - 64 (Glassdoor est.),3.2,CAS\n3.2,"Columbus, OH",1001 to 5000 Employees,1907,Subsidiary or Business Segment,Enterprise Software & Network Solutions,Information Technology,$100 to $500 million (USD)
5882,Supervisory Research Health Scientist,47 - 89 (Glassdoor est.),4.2,Centers for Disease Control and Prevention\n4.2,"Cincinnati, OH",10000+ Employees,1946,Government,Federal Agencies,Government,Unknown / Non-Applicable
5883,Senior SAS Programmer (Scientist),66 - 113 (Glassdoor est.),4.0,Certara\n4.0,"Cincinnati, OH",501 to 1000 Employees,2008,Company - Public,Biotech & Pharmaceuticals,Biotech & Pharmaceuticals,Unknown / Non-Applicable
5886,Senior Data Analyst - Product Analytics (open ...,67 - 111 (Glassdoor est.),4.0,New Relic\n4.0,"Cincinnati, OH",1001 to 5000 Employees,2008,Company - Public,Computer Hardware & Software,Information Technology,$100 to $500 million (USD)
5887,Manufacturing Data Analyst Engineer,42 - 76 (Glassdoor est.),3.6,Hose Master\n3.6,"Euclid, OH",201 to 500 Employees,1982,Company - Private,Electrical & Electronic Manufacturing,Manufacturing,Unknown / Non-Applicable

In [39]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 5526 entries, 0 to 5891
Data columns (total 11 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Job Title          5526 non-null   object
 1   Salary Estimate    5526 non-null   object
 2   Rating             5526 non-null   float64
 3   Company Name       5526 non-null   object
 4   Location           5526 non-null   object
 5   Size               5526 non-null   object
 6   Founded            5526 non-null   object
 7   Type of ownership  5526 non-null   object
 8   Industry           5526 non-null   object
 9   Sector             5526 non-null   object
 10  Revenue            5526 non-null   object
dtypes: float64(1), object(10)
memory usage: 518.1+ KB