<a href="https://colab.research.google.com/github/redsoil/Df_Ordering/blob/main/week5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import files

In [2]:
uploaded = files.upload()

Saving myDataFrame.csv to myDataFrame.csv

In [3]:
import pandas as pd

In [4]:
df = pd.read_csv('myDataFrame.csv')

In [5]:
df

,Unnamed: 0,Job Title,Salary Estimate,Rating,Company Name,Location,Size,Founded,Type of ownership,Industry,Sector,Revenue
0,0,Senior Data Scientist,111 - 181 (Glassdoor est.),3.5,Hopper\n3.5,"New York, NY",501 to 1000 employees,2007,Company - Private,Travel Agencies,Travel & Tourism,Unknown / Non-Applicable
1,1,"Data Scientist, Product Analytics",111 - 181 (Glassdoor est.),4.5,Noom US\n4.5,"New York, NY",1001 to 5000 employees,2008,Company - Private,"Health, Beauty, & Fitness",Consumer Services,Unknown / Non-Applicable
2,2,Data Science Manager,111 - 181 (Glassdoor est.),-1.0,Decode_M,"New York, NY",1 to 50 employees,-1,Unknown,-1,-1,Unknown / Non-Applicable
3,3,Data Analyst,111 - 181 (Glassdoor est.),3.4,Sapphire Digital\n3.4,"Lyndhurst, NJ",201 to 500 employees,2019,Company - Private,Internet,Information Technology,Unknown / Non-Applicable
4,4,"Director, Data Science",111 - 181 (Glassdoor est.),3.4,United Entertainment Group\n3.4,"New York, NY",51 to 200 employees,2007,Company - Private,Advertising & Marketing,Business Services,Unknown / Non-Applicable
...,...,...,...,...,...,...,...,...,...,...,...,...
5495,5881,Information Scientist,38 - 64 (Glassdoor est.),3.2,CAS\n3.2,"Columbus, OH",1001 to 5000 Employees,1907,Subsidiary or Business Segment,Enterprise Software & Network Solutions,Information Technology,$100 to $500 million (USD)
5496,5882,Supervisory Research Health Scientist,47 - 89 (Glassdoor est.),4.2,Centers for Disease Control and Prevention\n4.2,"Cincinnati, OH",10000+ Employees,1946,Government,Federal Agencies,Government,Unknown / Non-Applicable
5497,5883,Senior SAS Programmer (Scientist),66 - 113 (Glassdoor est.),4.0,Certara\n4.0,"Cincinnati, OH",501 to 1000 Employees,2008,Company - Public,Biotech & Pharmaceuticals,Biotech & Pharmaceuticals,Unknown / Non-Applicable
5498,5886,Senior Data Analyst - Product Analytics (open ...,67 - 111 (Glassdoor est.),4.0,New Relic\n4.0,"Cincinnati, OH",1001 to 5000 Employees,2008,Company - Public,Computer Hardware & Software,Information Technology,$100 to $500 million (USD)
5499,5887,Manufacturing Data Analyst Engineer,42 - 76 (Glassdoor est.),3.6,Hose Master\n3.6,"Euclid, OH",201 to 500 Employees,1982,Company - Private,Electrical & Electronic Manufacturing,Manufacturing,Unknown / Non-Applicable

In [6]:
df['Salary Estimate'][0].split()

['111', '-', '181', '(Glassdoor', 'est.)']

In [7]:
df['Salary Estimate'][0].split()[0]

'111'

In [8]:
df['Salary Estimate'][0].split()[2]

'181'

In [9]:
def splitter(a):
  a = a.split()
  return(a)

In [10]:
df['Salary Estimate']

0         111 - 181  (Glassdoor est.)
1         111 - 181  (Glassdoor est.)
2         111 - 181  (Glassdoor est.)
3         111 - 181  (Glassdoor est.)
4         111 - 181  (Glassdoor est.)
                    ...
5495      38  -  64  (Glassdoor est.)
5496      47  -  89  (Glassdoor est.)
5497     66  -  113  (Glassdoor est.)
5498     67  -  111  (Glassdoor est.)
5499      42  -  76  (Glassdoor est.)
Name: Salary Estimate, Length: 5500, dtype: object

In [11]:
df['Salary Estimate'].apply(splitter)

0       [111, -, 181, (Glassdoor, est.)]
1       [111, -, 181, (Glassdoor, est.)]
2       [111, -, 181, (Glassdoor, est.)]
3       [111, -, 181, (Glassdoor, est.)]
4       [111, -, 181, (Glassdoor, est.)]
                      ...
5495      [38, -, 64, (Glassdoor, est.)]
5496      [47, -, 89, (Glassdoor, est.)]
5497     [66, -, 113, (Glassdoor, est.)]
5498     [67, -, 111, (Glassdoor, est.)]
5499      [42, -, 76, (Glassdoor, est.)]
Name: Salary Estimate, Length: 5500, dtype: object

In [12]:
df['Salary Estimate'] = df['Salary Estimate'].apply(splitter)

In [13]:
df

,Unnamed: 0,Job Title,Salary Estimate,Rating,Company Name,Location,Size,Founded,Type of ownership,Industry,Sector,Revenue
0,0,Senior Data Scientist,"[111, -, 181, (Glassdoor, est.)]",3.5,Hopper\n3.5,"New York, NY",501 to 1000 employees,2007,Company - Private,Travel Agencies,Travel & Tourism,Unknown / Non-Applicable
1,1,"Data Scientist, Product Analytics","[111, -, 181, (Glassdoor, est.)]",4.5,Noom US\n4.5,"New York, NY",1001 to 5000 employees,2008,Company - Private,"Health, Beauty, & Fitness",Consumer Services,Unknown / Non-Applicable
2,2,Data Science Manager,"[111, -, 181, (Glassdoor, est.)]",-1.0,Decode_M,"New York, NY",1 to 50 employees,-1,Unknown,-1,-1,Unknown / Non-Applicable
3,3,Data Analyst,"[111, -, 181, (Glassdoor, est.)]",3.4,Sapphire Digital\n3.4,"Lyndhurst, NJ",201 to 500 employees,2019,Company - Private,Internet,Information Technology,Unknown / Non-Applicable
4,4,"Director, Data Science","[111, -, 181, (Glassdoor, est.)]",3.4,United Entertainment Group\n3.4,"New York, NY",51 to 200 employees,2007,Company - Private,Advertising & Marketing,Business Services,Unknown / Non-Applicable
...,...,...,...,...,...,...,...,...,...,...,...,...
5495,5881,Information Scientist,"[38, -, 64, (Glassdoor, est.)]",3.2,CAS\n3.2,"Columbus, OH",1001 to 5000 Employees,1907,Subsidiary or Business Segment,Enterprise Software & Network Solutions,Information Technology,$100 to $500 million (USD)
5496,5882,Supervisory Research Health Scientist,"[47, -, 89, (Glassdoor, est.)]",4.2,Centers for Disease Control and Prevention\n4.2,"Cincinnati, OH",10000+ Employees,1946,Government,Federal Agencies,Government,Unknown / Non-Applicable
5497,5883,Senior SAS Programmer (Scientist),"[66, -, 113, (Glassdoor, est.)]",4.0,Certara\n4.0,"Cincinnati, OH",501 to 1000 Employees,2008,Company - Public,Biotech & Pharmaceuticals,Biotech & Pharmaceuticals,Unknown / Non-Applicable
5498,5886,Senior Data Analyst - Product Analytics (open ...,"[67, -, 111, (Glassdoor, est.)]",4.0,New Relic\n4.0,"Cincinnati, OH",1001 to 5000 Employees,2008,Company - Public,Computer Hardware & Software,Information Technology,$100 to $500 million (USD)
5499,5887,Manufacturing Data Analyst Engineer,"[42, -, 76, (Glassdoor, est.)]",3.6,Hose Master\n3.6,"Euclid, OH",201 to 500 Employees,1982,Company - Private,Electrical & Electronic Manufacturing,Manufacturing,Unknown / Non-Applicable

In [14]:
def min_finder(a):
  a = a[0]
  return(a)

In [15]:
df['Salary Estimate'].apply(min_finder)

0       111
1       111
2       111
3       111
4       111
       ...
5495     38
5496     47
5497     66
5498     67
5499     42
Name: Salary Estimate, Length: 5500, dtype: object

In [16]:
df['Min_Salary'] = df['Salary Estimate'].apply(min_finder)

In [17]:
df

,Unnamed: 0,Job Title,Salary Estimate,Rating,Company Name,Location,Size,Founded,Type of ownership,Industry,Sector,Revenue,Min_Salary
0,0,Senior Data Scientist,"[111, -, 181, (Glassdoor, est.)]",3.5,Hopper\n3.5,"New York, NY",501 to 1000 employees,2007,Company - Private,Travel Agencies,Travel & Tourism,Unknown / Non-Applicable,111
1,1,"Data Scientist, Product Analytics","[111, -, 181, (Glassdoor, est.)]",4.5,Noom US\n4.5,"New York, NY",1001 to 5000 employees,2008,Company - Private,"Health, Beauty, & Fitness",Consumer Services,Unknown / Non-Applicable,111
2,2,Data Science Manager,"[111, -, 181, (Glassdoor, est.)]",-1.0,Decode_M,"New York, NY",1 to 50 employees,-1,Unknown,-1,-1,Unknown / Non-Applicable,111
3,3,Data Analyst,"[111, -, 181, (Glassdoor, est.)]",3.4,Sapphire Digital\n3.4,"Lyndhurst, NJ",201 to 500 employees,2019,Company - Private,Internet,Information Technology,Unknown / Non-Applicable,111
4,4,"Director, Data Science","[111, -, 181, (Glassdoor, est.)]",3.4,United Entertainment Group\n3.4,"New York, NY",51 to 200 employees,2007,Company - Private,Advertising & Marketing,Business Services,Unknown / Non-Applicable,111
...,...,...,...,...,...,...,...,...,...,...,...,...,...
5495,5881,Information Scientist,"[38, -, 64, (Glassdoor, est.)]",3.2,CAS\n3.2,"Columbus, OH",1001 to 5000 Employees,1907,Subsidiary or Business Segment,Enterprise Software & Network Solutions,Information Technology,$100 to $500 million (USD),38
5496,5882,Supervisory Research Health Scientist,"[47, -, 89, (Glassdoor, est.)]",4.2,Centers for Disease Control and Prevention\n4.2,"Cincinnati, OH",10000+ Employees,1946,Government,Federal Agencies,Government,Unknown / Non-Applicable,47
5497,5883,Senior SAS Programmer (Scientist),"[66, -, 113, (Glassdoor, est.)]",4.0,Certara\n4.0,"Cincinnati, OH",501 to 1000 Employees,2008,Company - Public,Biotech & Pharmaceuticals,Biotech & Pharmaceuticals,Unknown / Non-Applicable,66
5498,5886,Senior Data Analyst - Product Analytics (open ...,"[67, -, 111, (Glassdoor, est.)]",4.0,New Relic\n4.0,"Cincinnati, OH",1001 to 5000 Employees,2008,Company - Public,Computer Hardware & Software,Information Technology,$100 to $500 million (USD),67
5499,5887,Manufacturing Data Analyst Engineer,"[42, -, 76, (Glassdoor, est.)]",3.6,Hose Master\n3.6,"Euclid, OH",201 to 500 Employees,1982,Company - Private,Electrical & Electronic Manufacturing,Manufacturing,Unknown / Non-Applicable,42

In [18]:
def max_finder(a):
  a = a[2]
  return(a)

In [19]:
df['Salary Estimate'].apply(max_finder)

0       181
1       181
2       181
3       181
4       181
       ...
5495     64
5496     89
5497    113
5498    111
5499     76
Name: Salary Estimate, Length: 5500, dtype: object

In [20]:
df['Max_Salary'] = df['Salary Estimate'].apply(max_finder)

In [21]:
df

,Unnamed: 0,Job Title,Salary Estimate,Rating,Company Name,Location,Size,Founded,Type of ownership,Industry,Sector,Revenue,Min_Salary,Max_Salary
0,0,Senior Data Scientist,"[111, -, 181, (Glassdoor, est.)]",3.5,Hopper\n3.5,"New York, NY",501 to 1000 employees,2007,Company - Private,Travel Agencies,Travel & Tourism,Unknown / Non-Applicable,111,181
1,1,"Data Scientist, Product Analytics","[111, -, 181, (Glassdoor, est.)]",4.5,Noom US\n4.5,"New York, NY",1001 to 5000 employees,2008,Company - Private,"Health, Beauty, & Fitness",Consumer Services,Unknown / Non-Applicable,111,181
2,2,Data Science Manager,"[111, -, 181, (Glassdoor, est.)]",-1.0,Decode_M,"New York, NY",1 to 50 employees,-1,Unknown,-1,-1,Unknown / Non-Applicable,111,181
3,3,Data Analyst,"[111, -, 181, (Glassdoor, est.)]",3.4,Sapphire Digital\n3.4,"Lyndhurst, NJ",201 to 500 employees,2019,Company - Private,Internet,Information Technology,Unknown / Non-Applicable,111,181
4,4,"Director, Data Science","[111, -, 181, (Glassdoor, est.)]",3.4,United Entertainment Group\n3.4,"New York, NY",51 to 200 employees,2007,Company - Private,Advertising & Marketing,Business Services,Unknown / Non-Applicable,111,181
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5495,5881,Information Scientist,"[38, -, 64, (Glassdoor, est.)]",3.2,CAS\n3.2,"Columbus, OH",1001 to 5000 Employees,1907,Subsidiary or Business Segment,Enterprise Software & Network Solutions,Information Technology,$100 to $500 million (USD),38,64
5496,5882,Supervisory Research Health Scientist,"[47, -, 89, (Glassdoor, est.)]",4.2,Centers for Disease Control and Prevention\n4.2,"Cincinnati, OH",10000+ Employees,1946,Government,Federal Agencies,Government,Unknown / Non-Applicable,47,89
5497,5883,Senior SAS Programmer (Scientist),"[66, -, 113, (Glassdoor, est.)]",4.0,Certara\n4.0,"Cincinnati, OH",501 to 1000 Employees,2008,Company - Public,Biotech & Pharmaceuticals,Biotech & Pharmaceuticals,Unknown / Non-Applicable,66,113
5498,5886,Senior Data Analyst - Product Analytics (open ...,"[67, -, 111, (Glassdoor, est.)]",4.0,New Relic\n4.0,"Cincinnati, OH",1001 to 5000 Employees,2008,Company - Public,Computer Hardware & Software,Information Technology,$100 to $500 million (USD),67,111
5499,5887,Manufacturing Data Analyst Engineer,"[42, -, 76, (Glassdoor, est.)]",3.6,Hose Master\n3.6,"Euclid, OH",201 to 500 Employees,1982,Company - Private,Electrical & Electronic Manufacturing,Manufacturing,Unknown / Non-Applicable,42,76

In [22]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5500 entries, 0 to 5499
Data columns (total 14 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Unnamed: 0         5500 non-null   int64
 1   Job Title          5500 non-null   object
 2   Salary Estimate    5500 non-null   object
 3   Rating             5500 non-null   float64
 4   Company Name       5500 non-null   object
 5   Location           5500 non-null   object
 6   Size               5500 non-null   object
 7   Founded            5500 non-null   object
 8   Type of ownership  5500 non-null   object
 9   Industry           5500 non-null   object
 10  Sector             5500 non-null   object
 11  Revenue            5500 non-null   object
 12  Min_Salary         5500 non-null   object
 13  Max_Salary         5500 non-null   object
dtypes: float64(1), int64(1), object(12)
memory usage: 601.7+ KB

In [23]:
df.columns

Index(['Unnamed: 0', 'Job Title', 'Salary Estimate', 'Rating', 'Company Name',
       'Location', 'Size', 'Founded', 'Type of ownership', 'Industry',
       'Sector', 'Revenue', 'Min_Salary', 'Max_Salary'],
      dtype='object')

In [24]:
df.shape

(5500, 14)

In [25]:
df['Min_Salary'].astype(int)

0       111
1       111
2       111
3       111
4       111
       ...
5495     38
5496     47
5497     66
5498     67
5499     42
Name: Min_Salary, Length: 5500, dtype: int64

In [26]:
df['Min_Salary'] = df['Min_Salary'].astype(int)

In [27]:
df['Max_Salary'] = df['Max_Salary'].astype(int)

In [28]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5500 entries, 0 to 5499
Data columns (total 14 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Unnamed: 0         5500 non-null   int64
 1   Job Title          5500 non-null   object
 2   Salary Estimate    5500 non-null   object
 3   Rating             5500 non-null   float64
 4   Company Name       5500 non-null   object
 5   Location           5500 non-null   object
 6   Size               5500 non-null   object
 7   Founded            5500 non-null   object
 8   Type of ownership  5500 non-null   object
 9   Industry           5500 non-null   object
 10  Sector             5500 non-null   object
 11  Revenue            5500 non-null   object
 12  Min_Salary         5500 non-null   int64
 13  Max_Salary         5500 non-null   int64
dtypes: float64(1), int64(3), object(10)
memory usage: 601.7+ KB

In [29]:
df['Average_Salary'] = (df['Min_Salary'] + df['Max_Salary'])/2

In [30]:
df

,Unnamed: 0,Job Title,Salary Estimate,Rating,Company Name,Location,Size,Founded,Type of ownership,Industry,Sector,Revenue,Min_Salary,Max_Salary,Average_Salary
0,0,Senior Data Scientist,"[111, -, 181, (Glassdoor, est.)]",3.5,Hopper\n3.5,"New York, NY",501 to 1000 employees,2007,Company - Private,Travel Agencies,Travel & Tourism,Unknown / Non-Applicable,111,181,146.0
1,1,"Data Scientist, Product Analytics","[111, -, 181, (Glassdoor, est.)]",4.5,Noom US\n4.5,"New York, NY",1001 to 5000 employees,2008,Company - Private,"Health, Beauty, & Fitness",Consumer Services,Unknown / Non-Applicable,111,181,146.0
2,2,Data Science Manager,"[111, -, 181, (Glassdoor, est.)]",-1.0,Decode_M,"New York, NY",1 to 50 employees,-1,Unknown,-1,-1,Unknown / Non-Applicable,111,181,146.0
3,3,Data Analyst,"[111, -, 181, (Glassdoor, est.)]",3.4,Sapphire Digital\n3.4,"Lyndhurst, NJ",201 to 500 employees,2019,Company - Private,Internet,Information Technology,Unknown / Non-Applicable,111,181,146.0
4,4,"Director, Data Science","[111, -, 181, (Glassdoor, est.)]",3.4,United Entertainment Group\n3.4,"New York, NY",51 to 200 employees,2007,Company - Private,Advertising & Marketing,Business Services,Unknown / Non-Applicable,111,181,146.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5495,5881,Information Scientist,"[38, -, 64, (Glassdoor, est.)]",3.2,CAS\n3.2,"Columbus, OH",1001 to 5000 Employees,1907,Subsidiary or Business Segment,Enterprise Software & Network Solutions,Information Technology,$100 to $500 million (USD),38,64,51.0
5496,5882,Supervisory Research Health Scientist,"[47, -, 89, (Glassdoor, est.)]",4.2,Centers for Disease Control and Prevention\n4.2,"Cincinnati, OH",10000+ Employees,1946,Government,Federal Agencies,Government,Unknown / Non-Applicable,47,89,68.0
5497,5883,Senior SAS Programmer (Scientist),"[66, -, 113, (Glassdoor, est.)]",4.0,Certara\n4.0,"Cincinnati, OH",501 to 1000 Employees,2008,Company - Public,Biotech & Pharmaceuticals,Biotech & Pharmaceuticals,Unknown / Non-Applicable,66,113,89.5
5498,5886,Senior Data Analyst - Product Analytics (open ...,"[67, -, 111, (Glassdoor, est.)]",4.0,New Relic\n4.0,"Cincinnati, OH",1001 to 5000 Employees,2008,Company - Public,Computer Hardware & Software,Information Technology,$100 to $500 million (USD),67,111,89.0
5499,5887,Manufacturing Data Analyst Engineer,"[42, -, 76, (Glassdoor, est.)]",3.6,Hose Master\n3.6,"Euclid, OH",201 to 500 Employees,1982,Company - Private,Electrical & Electronic Manufacturing,Manufacturing,Unknown / Non-Applicable,42,76,59.0

In [31]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5500 entries, 0 to 5499
Data columns (total 15 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Unnamed: 0         5500 non-null   int64
 1   Job Title          5500 non-null   object
 2   Salary Estimate    5500 non-null   object
 3   Rating             5500 non-null   float64
 4   Company Name       5500 non-null   object
 5   Location           5500 non-null   object
 6   Size               5500 non-null   object
 7   Founded            5500 non-null   object
 8   Type of ownership  5500 non-null   object
 9   Industry           5500 non-null   object
 10  Sector             5500 non-null   object
 11  Revenue            5500 non-null   object
 12  Min_Salary         5500 non-null   int64
 13  Max_Salary         5500 non-null   int64
 14  Average_Salary     5500 non-null   float64
dtypes: float64(2), int64(3), object(10)
memory usage: 644.7+ KB

In [32]:
df['Location'].value_counts()

Location
Austin, TX          345
Chicago, IL         333
San Diego, CA       327
New York, NY        303
Los Angeles, CA     229
                   ...
Redlands, CA          1
Ladera Ranch, CA      1
Greenbelt, MD         1
Lanham, MD            1
Euclid, OH            1
Name: count, Length: 501, dtype: int64

In [33]:
df['Location'][0]

'New York, NY'

In [35]:
df['Location'][0].split()

['New', 'York,', 'NY']

In [36]:
df['Location'][0].split()[2]

'NY'

In [37]:
df['Location'][0].split()[-1]

'NY'

In [38]:
def state(a):
  a = a.split()
  a = a[-1]
  return(a)

In [39]:
state(df['Location'][0])

'NY'

In [40]:
df['State'] = df['Location'].apply(state)

In [41]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5500 entries, 0 to 5499
Data columns (total 16 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Unnamed: 0         5500 non-null   int64
 1   Job Title          5500 non-null   object
 2   Salary Estimate    5500 non-null   object
 3   Rating             5500 non-null   float64
 4   Company Name       5500 non-null   object
 5   Location           5500 non-null   object
 6   Size               5500 non-null   object
 7   Founded            5500 non-null   object
 8   Type of ownership  5500 non-null   object
 9   Industry           5500 non-null   object
 10  Sector             5500 non-null   object
 11  Revenue            5500 non-null   object
 12  Min_Salary         5500 non-null   int64
 13  Max_Salary         5500 non-null   int64
 14  Average_Salary     5500 non-null   float64
 15  State              5500 non-null   object
dtypes: float64(2), int64(3), object(11)
memory usage: 687.6+ KB

In [42]:
df

,Unnamed: 0,Job Title,Salary Estimate,Rating,Company Name,Location,Size,Founded,Type of ownership,Industry,Sector,Revenue,Min_Salary,Max_Salary,Average_Salary,State
0,0,Senior Data Scientist,"[111, -, 181, (Glassdoor, est.)]",3.5,Hopper\n3.5,"New York, NY",501 to 1000 employees,2007,Company - Private,Travel Agencies,Travel & Tourism,Unknown / Non-Applicable,111,181,146.0,NY
1,1,"Data Scientist, Product Analytics","[111, -, 181, (Glassdoor, est.)]",4.5,Noom US\n4.5,"New York, NY",1001 to 5000 employees,2008,Company - Private,"Health, Beauty, & Fitness",Consumer Services,Unknown / Non-Applicable,111,181,146.0,NY
2,2,Data Science Manager,"[111, -, 181, (Glassdoor, est.)]",-1.0,Decode_M,"New York, NY",1 to 50 employees,-1,Unknown,-1,-1,Unknown / Non-Applicable,111,181,146.0,NY
3,3,Data Analyst,"[111, -, 181, (Glassdoor, est.)]",3.4,Sapphire Digital\n3.4,"Lyndhurst, NJ",201 to 500 employees,2019,Company - Private,Internet,Information Technology,Unknown / Non-Applicable,111,181,146.0,NJ
4,4,"Director, Data Science","[111, -, 181, (Glassdoor, est.)]",3.4,United Entertainment Group\n3.4,"New York, NY",51 to 200 employees,2007,Company - Private,Advertising & Marketing,Business Services,Unknown / Non-Applicable,111,181,146.0,NY
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5495,5881,Information Scientist,"[38, -, 64, (Glassdoor, est.)]",3.2,CAS\n3.2,"Columbus, OH",1001 to 5000 Employees,1907,Subsidiary or Business Segment,Enterprise Software & Network Solutions,Information Technology,$100 to $500 million (USD),38,64,51.0,OH
5496,5882,Supervisory Research Health Scientist,"[47, -, 89, (Glassdoor, est.)]",4.2,Centers for Disease Control and Prevention\n4.2,"Cincinnati, OH",10000+ Employees,1946,Government,Federal Agencies,Government,Unknown / Non-Applicable,47,89,68.0,OH
5497,5883,Senior SAS Programmer (Scientist),"[66, -, 113, (Glassdoor, est.)]",4.0,Certara\n4.0,"Cincinnati, OH",501 to 1000 Employees,2008,Company - Public,Biotech & Pharmaceuticals,Biotech & Pharmaceuticals,Unknown / Non-Applicable,66,113,89.5,OH
5498,5886,Senior Data Analyst - Product Analytics (open ...,"[67, -, 111, (Glassdoor, est.)]",4.0,New Relic\n4.0,"Cincinnati, OH",1001 to 5000 Employees,2008,Company - Public,Computer Hardware & Software,Information Technology,$100 to $500 million (USD),67,111,89.0,OH
5499,5887,Manufacturing Data Analyst Engineer,"[42, -, 76, (Glassdoor, est.)]",3.6,Hose Master\n3.6,"Euclid, OH",201 to 500 Employees,1982,Company - Private,Electrical & Electronic Manufacturing,Manufacturing,Unknown / Non-Applicable,42,76,59.0,OH

In [43]:
df['State'].value_counts()

State
CA         1311
TX         1243
OH          408
IL          368
PA          324
NY          313
AZ          297
FL          261
MA          239
NJ          232
MI          203
VA          131
DC           85
MD           61
DE           10
Kingdom       4
WI            3
GA            1
ME            1
KY            1
NM            1
NH            1
IN            1
NC            1
Name: count, dtype: int64

In [46]:
df[df['State'] != 'Kingdom']

,Unnamed: 0,Job Title,Salary Estimate,Rating,Company Name,Location,Size,Founded,Type of ownership,Industry,Sector,Revenue,Min_Salary,Max_Salary,Average_Salary,State
0,0,Senior Data Scientist,"[111, -, 181, (Glassdoor, est.)]",3.5,Hopper\n3.5,"New York, NY",501 to 1000 employees,2007,Company - Private,Travel Agencies,Travel & Tourism,Unknown / Non-Applicable,111,181,146.0,NY
1,1,"Data Scientist, Product Analytics","[111, -, 181, (Glassdoor, est.)]",4.5,Noom US\n4.5,"New York, NY",1001 to 5000 employees,2008,Company - Private,"Health, Beauty, & Fitness",Consumer Services,Unknown / Non-Applicable,111,181,146.0,NY
2,2,Data Science Manager,"[111, -, 181, (Glassdoor, est.)]",-1.0,Decode_M,"New York, NY",1 to 50 employees,-1,Unknown,-1,-1,Unknown / Non-Applicable,111,181,146.0,NY
3,3,Data Analyst,"[111, -, 181, (Glassdoor, est.)]",3.4,Sapphire Digital\n3.4,"Lyndhurst, NJ",201 to 500 employees,2019,Company - Private,Internet,Information Technology,Unknown / Non-Applicable,111,181,146.0,NJ
4,4,"Director, Data Science","[111, -, 181, (Glassdoor, est.)]",3.4,United Entertainment Group\n3.4,"New York, NY",51 to 200 employees,2007,Company - Private,Advertising & Marketing,Business Services,Unknown / Non-Applicable,111,181,146.0,NY
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5495,5881,Information Scientist,"[38, -, 64, (Glassdoor, est.)]",3.2,CAS\n3.2,"Columbus, OH",1001 to 5000 Employees,1907,Subsidiary or Business Segment,Enterprise Software & Network Solutions,Information Technology,$100 to $500 million (USD),38,64,51.0,OH
5496,5882,Supervisory Research Health Scientist,"[47, -, 89, (Glassdoor, est.)]",4.2,Centers for Disease Control and Prevention\n4.2,"Cincinnati, OH",10000+ Employees,1946,Government,Federal Agencies,Government,Unknown / Non-Applicable,47,89,68.0,OH
5497,5883,Senior SAS Programmer (Scientist),"[66, -, 113, (Glassdoor, est.)]",4.0,Certara\n4.0,"Cincinnati, OH",501 to 1000 Employees,2008,Company - Public,Biotech & Pharmaceuticals,Biotech & Pharmaceuticals,Unknown / Non-Applicable,66,113,89.5,OH
5498,5886,Senior Data Analyst - Product Analytics (open ...,"[67, -, 111, (Glassdoor, est.)]",4.0,New Relic\n4.0,"Cincinnati, OH",1001 to 5000 Employees,2008,Company - Public,Computer Hardware & Software,Information Technology,$100 to $500 million (USD),67,111,89.0,OH
5499,5887,Manufacturing Data Analyst Engineer,"[42, -, 76, (Glassdoor, est.)]",3.6,Hose Master\n3.6,"Euclid, OH",201 to 500 Employees,1982,Company - Private,Electrical & Electronic Manufacturing,Manufacturing,Unknown / Non-Applicable,42,76,59.0,OH

In [47]:
df

,Unnamed: 0,Job Title,Salary Estimate,Rating,Company Name,Location,Size,Founded,Type of ownership,Industry,Sector,Revenue,Min_Salary,Max_Salary,Average_Salary,State
0,0,Senior Data Scientist,"[111, -, 181, (Glassdoor, est.)]",3.5,Hopper\n3.5,"New York, NY",501 to 1000 employees,2007,Company - Private,Travel Agencies,Travel & Tourism,Unknown / Non-Applicable,111,181,146.0,NY
1,1,"Data Scientist, Product Analytics","[111, -, 181, (Glassdoor, est.)]",4.5,Noom US\n4.5,"New York, NY",1001 to 5000 employees,2008,Company - Private,"Health, Beauty, & Fitness",Consumer Services,Unknown / Non-Applicable,111,181,146.0,NY
2,2,Data Science Manager,"[111, -, 181, (Glassdoor, est.)]",-1.0,Decode_M,"New York, NY",1 to 50 employees,-1,Unknown,-1,-1,Unknown / Non-Applicable,111,181,146.0,NY
3,3,Data Analyst,"[111, -, 181, (Glassdoor, est.)]",3.4,Sapphire Digital\n3.4,"Lyndhurst, NJ",201 to 500 employees,2019,Company - Private,Internet,Information Technology,Unknown / Non-Applicable,111,181,146.0,NJ
4,4,"Director, Data Science","[111, -, 181, (Glassdoor, est.)]",3.4,United Entertainment Group\n3.4,"New York, NY",51 to 200 employees,2007,Company - Private,Advertising & Marketing,Business Services,Unknown / Non-Applicable,111,181,146.0,NY
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5495,5881,Information Scientist,"[38, -, 64, (Glassdoor, est.)]",3.2,CAS\n3.2,"Columbus, OH",1001 to 5000 Employees,1907,Subsidiary or Business Segment,Enterprise Software & Network Solutions,Information Technology,$100 to $500 million (USD),38,64,51.0,OH
5496,5882,Supervisory Research Health Scientist,"[47, -, 89, (Glassdoor, est.)]",4.2,Centers for Disease Control and Prevention\n4.2,"Cincinnati, OH",10000+ Employees,1946,Government,Federal Agencies,Government,Unknown / Non-Applicable,47,89,68.0,OH
5497,5883,Senior SAS Programmer (Scientist),"[66, -, 113, (Glassdoor, est.)]",4.0,Certara\n4.0,"Cincinnati, OH",501 to 1000 Employees,2008,Company - Public,Biotech & Pharmaceuticals,Biotech & Pharmaceuticals,Unknown / Non-Applicable,66,113,89.5,OH
5498,5886,Senior Data Analyst - Product Analytics (open ...,"[67, -, 111, (Glassdoor, est.)]",4.0,New Relic\n4.0,"Cincinnati, OH",1001 to 5000 Employees,2008,Company - Public,Computer Hardware & Software,Information Technology,$100 to $500 million (USD),67,111,89.0,OH
5499,5887,Manufacturing Data Analyst Engineer,"[42, -, 76, (Glassdoor, est.)]",3.6,Hose Master\n3.6,"Euclid, OH",201 to 500 Employees,1982,Company - Private,Electrical & Electronic Manufacturing,Manufacturing,Unknown / Non-Applicable,42,76,59.0,OH

In [49]:
df = df[df['State'] != 'Kingdom']

In [50]:
df

,Unnamed: 0,Job Title,Salary Estimate,Rating,Company Name,Location,Size,Founded,Type of ownership,Industry,Sector,Revenue,Min_Salary,Max_Salary,Average_Salary,State
0,0,Senior Data Scientist,"[111, -, 181, (Glassdoor, est.)]",3.5,Hopper\n3.5,"New York, NY",501 to 1000 employees,2007,Company - Private,Travel Agencies,Travel & Tourism,Unknown / Non-Applicable,111,181,146.0,NY
1,1,"Data Scientist, Product Analytics","[111, -, 181, (Glassdoor, est.)]",4.5,Noom US\n4.5,"New York, NY",1001 to 5000 employees,2008,Company - Private,"Health, Beauty, & Fitness",Consumer Services,Unknown / Non-Applicable,111,181,146.0,NY
2,2,Data Science Manager,"[111, -, 181, (Glassdoor, est.)]",-1.0,Decode_M,"New York, NY",1 to 50 employees,-1,Unknown,-1,-1,Unknown / Non-Applicable,111,181,146.0,NY
3,3,Data Analyst,"[111, -, 181, (Glassdoor, est.)]",3.4,Sapphire Digital\n3.4,"Lyndhurst, NJ",201 to 500 employees,2019,Company - Private,Internet,Information Technology,Unknown / Non-Applicable,111,181,146.0,NJ
4,4,"Director, Data Science","[111, -, 181, (Glassdoor, est.)]",3.4,United Entertainment Group\n3.4,"New York, NY",51 to 200 employees,2007,Company - Private,Advertising & Marketing,Business Services,Unknown / Non-Applicable,111,181,146.0,NY
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5495,5881,Information Scientist,"[38, -, 64, (Glassdoor, est.)]",3.2,CAS\n3.2,"Columbus, OH",1001 to 5000 Employees,1907,Subsidiary or Business Segment,Enterprise Software & Network Solutions,Information Technology,$100 to $500 million (USD),38,64,51.0,OH
5496,5882,Supervisory Research Health Scientist,"[47, -, 89, (Glassdoor, est.)]",4.2,Centers for Disease Control and Prevention\n4.2,"Cincinnati, OH",10000+ Employees,1946,Government,Federal Agencies,Government,Unknown / Non-Applicable,47,89,68.0,OH
5497,5883,Senior SAS Programmer (Scientist),"[66, -, 113, (Glassdoor, est.)]",4.0,Certara\n4.0,"Cincinnati, OH",501 to 1000 Employees,2008,Company - Public,Biotech & Pharmaceuticals,Biotech & Pharmaceuticals,Unknown / Non-Applicable,66,113,89.5,OH
5498,5886,Senior Data Analyst - Product Analytics (open ...,"[67, -, 111, (Glassdoor, est.)]",4.0,New Relic\n4.0,"Cincinnati, OH",1001 to 5000 Employees,2008,Company - Public,Computer Hardware & Software,Information Technology,$100 to $500 million (USD),67,111,89.0,OH
5499,5887,Manufacturing Data Analyst Engineer,"[42, -, 76, (Glassdoor, est.)]",3.6,Hose Master\n3.6,"Euclid, OH",201 to 500 Employees,1982,Company - Private,Electrical & Electronic Manufacturing,Manufacturing,Unknown / Non-Applicable,42,76,59.0,OH

In [51]:
df[df['Rating'] != -1]

,Unnamed: 0,Job Title,Salary Estimate,Rating,Company Name,Location,Size,Founded,Type of ownership,Industry,Sector,Revenue,Min_Salary,Max_Salary,Average_Salary,State
0,0,Senior Data Scientist,"[111, -, 181, (Glassdoor, est.)]",3.5,Hopper\n3.5,"New York, NY",501 to 1000 employees,2007,Company - Private,Travel Agencies,Travel & Tourism,Unknown / Non-Applicable,111,181,146.0,NY
1,1,"Data Scientist, Product Analytics","[111, -, 181, (Glassdoor, est.)]",4.5,Noom US\n4.5,"New York, NY",1001 to 5000 employees,2008,Company - Private,"Health, Beauty, & Fitness",Consumer Services,Unknown / Non-Applicable,111,181,146.0,NY
3,3,Data Analyst,"[111, -, 181, (Glassdoor, est.)]",3.4,Sapphire Digital\n3.4,"Lyndhurst, NJ",201 to 500 employees,2019,Company - Private,Internet,Information Technology,Unknown / Non-Applicable,111,181,146.0,NJ
4,4,"Director, Data Science","[111, -, 181, (Glassdoor, est.)]",3.4,United Entertainment Group\n3.4,"New York, NY",51 to 200 employees,2007,Company - Private,Advertising & Marketing,Business Services,Unknown / Non-Applicable,111,181,146.0,NY
5,5,Data Scientist,"[111, -, 181, (Glassdoor, est.)]",2.9,IFG Companies\n2.9,"New York, NY",201 to 500 employees,1985,Company - Private,Insurance Carriers,Insurance,Unknown / Non-Applicable,111,181,146.0,NY
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5495,5881,Information Scientist,"[38, -, 64, (Glassdoor, est.)]",3.2,CAS\n3.2,"Columbus, OH",1001 to 5000 Employees,1907,Subsidiary or Business Segment,Enterprise Software & Network Solutions,Information Technology,$100 to $500 million (USD),38,64,51.0,OH
5496,5882,Supervisory Research Health Scientist,"[47, -, 89, (Glassdoor, est.)]",4.2,Centers for Disease Control and Prevention\n4.2,"Cincinnati, OH",10000+ Employees,1946,Government,Federal Agencies,Government,Unknown / Non-Applicable,47,89,68.0,OH
5497,5883,Senior SAS Programmer (Scientist),"[66, -, 113, (Glassdoor, est.)]",4.0,Certara\n4.0,"Cincinnati, OH",501 to 1000 Employees,2008,Company - Public,Biotech & Pharmaceuticals,Biotech & Pharmaceuticals,Unknown / Non-Applicable,66,113,89.5,OH
5498,5886,Senior Data Analyst - Product Analytics (open ...,"[67, -, 111, (Glassdoor, est.)]",4.0,New Relic\n4.0,"Cincinnati, OH",1001 to 5000 Employees,2008,Company - Public,Computer Hardware & Software,Information Technology,$100 to $500 million (USD),67,111,89.0,OH
5499,5887,Manufacturing Data Analyst Engineer,"[42, -, 76, (Glassdoor, est.)]",3.6,Hose Master\n3.6,"Euclid, OH",201 to 500 Employees,1982,Company - Private,Electrical & Electronic Manufacturing,Manufacturing,Unknown / Non-Applicable,42,76,59.0,OH

In [52]:
df = df[df['Rating'] != -1]

In [53]:
df

,Unnamed: 0,Job Title,Salary Estimate,Rating,Company Name,Location,Size,Founded,Type of ownership,Industry,Sector,Revenue,Min_Salary,Max_Salary,Average_Salary,State
0,0,Senior Data Scientist,"[111, -, 181, (Glassdoor, est.)]",3.5,Hopper\n3.5,"New York, NY",501 to 1000 employees,2007,Company - Private,Travel Agencies,Travel & Tourism,Unknown / Non-Applicable,111,181,146.0,NY
1,1,"Data Scientist, Product Analytics","[111, -, 181, (Glassdoor, est.)]",4.5,Noom US\n4.5,"New York, NY",1001 to 5000 employees,2008,Company - Private,"Health, Beauty, & Fitness",Consumer Services,Unknown / Non-Applicable,111,181,146.0,NY
3,3,Data Analyst,"[111, -, 181, (Glassdoor, est.)]",3.4,Sapphire Digital\n3.4,"Lyndhurst, NJ",201 to 500 employees,2019,Company - Private,Internet,Information Technology,Unknown / Non-Applicable,111,181,146.0,NJ
4,4,"Director, Data Science","[111, -, 181, (Glassdoor, est.)]",3.4,United Entertainment Group\n3.4,"New York, NY",51 to 200 employees,2007,Company - Private,Advertising & Marketing,Business Services,Unknown / Non-Applicable,111,181,146.0,NY
5,5,Data Scientist,"[111, -, 181, (Glassdoor, est.)]",2.9,IFG Companies\n2.9,"New York, NY",201 to 500 employees,1985,Company - Private,Insurance Carriers,Insurance,Unknown / Non-Applicable,111,181,146.0,NY
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5495,5881,Information Scientist,"[38, -, 64, (Glassdoor, est.)]",3.2,CAS\n3.2,"Columbus, OH",1001 to 5000 Employees,1907,Subsidiary or Business Segment,Enterprise Software & Network Solutions,Information Technology,$100 to $500 million (USD),38,64,51.0,OH
5496,5882,Supervisory Research Health Scientist,"[47, -, 89, (Glassdoor, est.)]",4.2,Centers for Disease Control and Prevention\n4.2,"Cincinnati, OH",10000+ Employees,1946,Government,Federal Agencies,Government,Unknown / Non-Applicable,47,89,68.0,OH
5497,5883,Senior SAS Programmer (Scientist),"[66, -, 113, (Glassdoor, est.)]",4.0,Certara\n4.0,"Cincinnati, OH",501 to 1000 Employees,2008,Company - Public,Biotech & Pharmaceuticals,Biotech & Pharmaceuticals,Unknown / Non-Applicable,66,113,89.5,OH
5498,5886,Senior Data Analyst - Product Analytics (open ...,"[67, -, 111, (Glassdoor, est.)]",4.0,New Relic\n4.0,"Cincinnati, OH",1001 to 5000 Employees,2008,Company - Public,Computer Hardware & Software,Information Technology,$100 to $500 million (USD),67,111,89.0,OH
5499,5887,Manufacturing Data Analyst Engineer,"[42, -, 76, (Glassdoor, est.)]",3.6,Hose Master\n3.6,"Euclid, OH",201 to 500 Employees,1982,Company - Private,Electrical & Electronic Manufacturing,Manufacturing,Unknown / Non-Applicable,42,76,59.0,OH

In [54]:
df['Job Title'].value_counts()

Job Title
Data Scientist                                                   530
Data Analyst                                                     296
Data Engineer                                                    267
Senior Data Scientist                                            117
Machine Learning Engineer                                         55
                                                                ...
Data Scientist - Top Secret w/ SCI Eligibility                     1
Business Intelligence Analyst I                                    1
Business Intelligence Analyst Senior (Chief Financial Office)      1
Business Intelligence Analyst III - Credit Card                    1
Manufacturing Data Analyst Engineer                                1
Name: count, Length: 2552, dtype: int64

In [55]:
set(df['Job Title'])

{'Computer Vision / Machine Learning Engineer',
 'Data Analyst/Data Entry/Federal Data Entry/Data Specialist',
 'Web Analytics Manager',
 'Big Data Engineer (OH)',
 'CLINICAL LABORATORY SCIENTIST',
 'Associate Data Scientist',
 'Health Data Scientist',
 'MRI Associate Principal Scientist',
 'Data Scientist, Intern',
 'Machine Learning Engineer - HBO Max',
 'Data Scientist, Business Information Services',
 'Principal Scientist, Medicinal Chemistry - Discovery Chemistry',
 'AI Insights Data Analyst',
 'Data Scientist – Computer Vision',
 'Small Business Lending Data Scientist',
 'Quantitative Research Analyst - Experienced Hire',
 'Data Analyst / Developer',
 'Senior Data Scientist, Product Analytics',
 'Consultant - Advanced Solutions, Energy Data Scientist - Campus 2021',
 'Installation Data Analyst',
 'Provider Data Analyst',
 'Data Scientist - Cruises & Events',
 'Scientist-Web Developer',
 'Principal Data Scientist - R&D Oncology',
 'Associate Scientist ( Immuno-Oncology)',
 'Data Scientist Retail Optimization',
 'Data Scientist - Fraud Engineering, Algorithms, and Risk',
 'Senior Data Science Manager',
 'Data Engineer/ Big Data Engineer',
 'BI Data Analyst/Specialist',
 'Data & Machine Learning Scientist',
 'Software Engineer (Data Scientist, C,C++,Linux,Unix) - SISW - MG',
 'DATA SCIENTIST (Performance Reporting)',
 'Data Scientist / AI Engineer',
 'Data Engineer Associate',
 'Data Engineer for Industrial Image Data - Columbus, OH',
 'Senior Scientist - Immunotherapeutic Design',
 'Financial Quantitative Analyst',
 'Remote Senior Software Engineer, Data',
 'Data Scientist - Lab222',
 'Live Operations Data Analyst',
 'Principal Data Scientist- Ensemble Algorithms and Architecture',
 'AI/Data Scientist, R&D',
 'ELISA Scientist',
 'Data Analyst - (Python)',
 'Analytics Consultant',
 'Scientist - HLA Laboratory',
 'Data Engineer (Azure Delta Lake and Databricks)',
 'Scientist Web Developer',
 'Marketing Data Scientist',
 'Data Analyst, Budget & Management, Security Customer Success',
 'Revenue Management and Strategic Analytics Manager',
 'Clinical Laboratory Scientist, Nights, Full Time - $20K Sign On Bonus!',
 'Demand Planning and Analytics, Manager',
 'Sr. Computational Biologist, Immuno-Oncology',
 'Data Analyst- Remote',
 'Data Engineer-Journeyman',
 'Assistant, Associate or Full Research Scientist - Head of the Human Liver Cell Isolation Lab',
 'Data Scientist Risk Analyst',
 'Data Scientist 2 - Styling/Trunks Data Science & Analytics',
 'Associate or Scientist, In Vivo Pharmacology and Clinical Virology',
 'Medical Lab Scientist (MLS) AM/PM',
 'Data Scientist - DCCA',
 'JPMWM - CARE - Data Scientist - Associate',
 'Computer Vision Scientist',
 'Business Intelligence - Data Analyst',
 'Data Engineer Hadoop',
 'Scientist - Large Molecule',
 'Salesforce Business Intelligence Analyst II',
 'Data Analyst- Digital',
 'Lead Data Scientist - NJ/NY based',
 'Data Scientist - BFSI',
 'Data Scientist - Sr. Analyst',
 'Data Analyst - Performance Improvement Operations',
 'Data Engineer- Python',
 'Associate Integration Scientist 1',
 'Scientist / Associate Scientist, Cancer Immunotherapy',
 'Basel Data Analyst',
 'Medical Laboratory Scientist - Immuno Diagnostics - Evening Shift',
 'Senior Data Scientist, Ad Platforms',
 'Business Strategy and Planning Director - Data Science Strategy',
 'Test Data Engineer',
 'Lead/Principal Data Engineer',
 'The Home Depot PRO - Data Analyst',
 'Data Modeler Architect',
 'Architect, Data Intelligence',
 'Customer Service Supervisor (Medical Lab Scientist)',
 'Post-Doctoral Magnetic Resonance Research Scientist',
 'Data Scientist – Service Demand Planning',
 'Data Engineer For Industrial Image Data',
 'Data Analytics Architect',
 'Data Scientist - Disney Streaming Services',
 'Data Scientist 3 (Tableau Statistics (Fleet Readiness), Tableau Statistics (IT Portfolio), Predictive Analysis & Visualization)',
 'Molecular Engineering Senior Research Scientist',
 'Computer Research Scientist',
 'Maps Search Machine Learning Engineer',
 'Data Analyst (Kronos) - Ohio Location Only',
 'Senior Scientist, Process Science - Analytical Sciences',
 'Sr. Data Scientist/AI Scientist',
 'Data Analyst, Predictive Analytics',
 'Applied Research Scientist - Computer Vision',
 'Human Factors Scientist',
 'Principal Scientist, Translational Bioinformatics Late Stage Immunology, Cardiovascular and Fibrosis',
 'SAS Data Analyst III(With SOL & Tableau)',
 'Senior Scientist, QC Flow Cytometry',
 'Data Scientist, Analytics - AR/VR Portal',
 'Business Data Analyst III',
 'Data Science Software Engineer',
 'Actuary - Data Science & Advanced Analytics',
 'Vice President, Director, Data Science',
 'Scientist, QC Flow Cytometry',
 'Applied Data Scientist',
 'Data Scientists',
 'Sr. Scientist',
 'Data Scientist (DoD Secret Security Clearance)',
 'Network Data Analyst',
 'Healthcare Data Analytics PhD / Sr. Data Scientist',
 'Behavioral Data Science Manager',
 'Research Scientist I-III',
 'Director II - Data Science at Solaria Labs',
 'Data Analyst - New York Life Investments',
 'Consultant, Analytic Scientist (Model Steward)',
 'Applied Data Scientist, Government',
 'Senior Scientist, Neuroscience',
 'Senior Scientist, Vaccine Process Development and Commercialization (Downstream)',
 'Business Intelligence Analytics Manager',
 'Associate Scientist, Bioinformatics',
 'Senior Scientist, Scientific Affairs',
 'Staff Software Scientist, Reproductive Health',
 'Staff Big Data Engineer',
 'Lead Quality Data Analyst',
 'Quantitative Analyst – Model Validation',
 'Manufacturing Data Analyst (Entry level)',
 'Azure Data Engineer- Houston TX',
 'Clinical Laboratory Scientist, Per Diem',
 'Intern- Martech & Data Consulting',
 'Data Scientist (Fintech)',
 'CIB - Data Scientist',
 'Data Scientist, Life Solutions',
 'Senior Data Scientist - Optimization',
 'Data Scientist, Analytics',
 'Strategic Data Analyst III - Strategic Planning Divsion',
 'Senior Data Engineer - Information Security',
 'Data Scientist - ProServe',
 'Field Appl Scientist I',
 'Research Scientist - Robotic Manufacturing',
 'Senior Data Scientist, FP&A',
 'Senior Data Scientist-Healthcare',
 'NGS Scientist',
 'Data Academy Lead (Business Intelligence Analyst/Developer)',
 'Marketing & Data Analyst',
 'Sr Analyst, Data Scientist Business Intelligence (1 of 2 Openings)',
 'IS Data Architect',
 'Senior Environmental Scientist Part Time',
 'Director II, Data Science',
 'Power & Performance Data Engineer',
 'Network Security System/Data Analyst',
 'Medical Laboratory Scientist - Core Lab - Part-Time',
 'COMPUTER SCIENTIST - ENGINEER - DECISION TECHNOLOGIES',
 'Scientist Medical Laboratory II',
 'Data Engineer / Python Developer',
 'Senior Research Scientist Specializing in Machine Learning',
 'IoT Data Scientist - Leadeship Role - Chicago, NY, Dallas, or Atlanta',
 'Sr. Data Software Engineer',
 'Data Analyst (Apex Legends)',
 'Snowflake Data Engineer',
 'Data Architect /Data Modeler/Data Analyst',
 'Senior Data Science Consultant',
 'Roche Postdoctoral Fellowship (RPF), Cancer Immunotherapy, Reverse Translation Data Scientist',
 'Lead Data Engineer (St. Louis, Austin or Toronto)',
 'Microsoft Analytics Consultant',
 'Data Scientist, Jr',
 'Sr. Data Scientist - TS/SCI',
 'Sr. Business Data Analyst - Enterprise Risk',
 '098: Data Engineer',
 'Quant Analytics Manager (DAQA07) SALES SCIENCE',
 'Scientist III (Molecular Biology)',
 'Principal Scientist Product Formulation',
 'Associate Scientist: Drug product development',
 'Staff Business Intelligence Analyst',
 'Manager, Real Estate Data Science & Strategy',
 'Lead Process Development Scientist - Upstream',
 'Call Center Analytics Manager',
 'Data Architect - Salesforce',
 'Phoenix Data Science Tutor Jobs',
 'Senior Upstream Processing Scientist',
 'Data Scientist, Instagram - Well-being, Trust',
 'Data Scientist/Data Engineer',
 'Data Analyst Senior',
 'Adjunct Faculty - Advanced Quantitative Research Design and Analysis',
 'Senior Associate Scientist, Biophysical Screening',
 '2021 Global Data Science Advanced Graduate ML Track Co-Op',
 'Data Scientist, Buyer Experience',
 'Data Scientist – Product Analytics',
 'Asbestos Environmental Scientist',
 'Principal Data Engineering Architect - Data Pipelines',
 'Scientific Data Analyst – Junior',
 'Quantitative Analyst - Asset Allocation Analyst',
 'Data Science Tutoring/Teaching',
 'Principal/Senior Data Engineer - Finance',
 'Pipeline Integrity – Data Scientist',
 'Data Engineer- Guidewire Data Hub',
 'Data Scientist with Security Clearance',
 'Data Analyst Junior',
 'Austin Data Science Tutor Jobs',
 'Scientist III, QC Aero Star 2nd Shift',
 'Salesforce Data Analyst',
 'Data Analyst - Medicare',
 'Data Scientist, Finance',
 'Data Scientist - Weather Data',
 'Data Scientist Associate Sr (DADS06) CCB ML & AI',
 'Data Scientist 2',
 'Formulation development Sr Scientist',
 'Data Analyst, Quality Management Systems',
 'Field Geologist/ Scientist I',
 'CIB QR- Quantitative Research - Wholesale Credit Capital Modeling - Quantitative Developer - Vice Pr',
 'Post Doctoral Scientist - Motor Neuron Gene Therapy',
 'RESEARCH COMPUTER SCIENTIST - RESEARCH ENGINEER - SR. COMPUTER SCIENTIST - SIGNAL PROCESSING',
 'Business Facing Data Analyst',
 'Principal Data Scientist- Public Sector',
 'Production Scientist',
 'JPSC-6455 - Big Data Engineer with HL7 Healthcare/Python',
 'Scientist I, Formulation',
 'Data Analyst | Informational And Statistical Analyst',
 'Risk Data Analyst',
 'Senior Data Scientist - Opportunity for Working Remotely Washington, D.C.',
 'Research Scientist/Senior Research Scientist - Surgery and Efficacy Study Directors',
 'Quantum Principal Data Scientist (Industrial-Process sector)',
 'Medical Lab Scientist License Pending',
 'Staff Scientist',
 'Principal Data Scientist-- Ensemble Algorithms and Architecture',
 'Machine Learning and Data Engineer - South Florida',
 'Software Engineer, Data Warehousing',
 'Research Scientist - Neural Interfaces',
 'Clinical Lab Scientist',
 'Sr. Data Engineer (OPT EAD, GC, GC EAD, USC and TN)',
 'Sales Operations - Data Scientist',
 'Senior Program & Engagement Officer, Data Science & Next-generation Metadata',
 'Senior Data Analyst, Disney+',
 'Risk Analytics Manager',
 'IT Data Engineer with Data Catalog',
 'Senior Global Data Analyst / Power BI Dashboard Developer',
 'San Antonio Data Science Tutor Jobs',
 'Product Data Engineer - GPU',
 'Big data engineer',
 'Data Analyst - IntelliScript',
 'Principal Data Scientist, Pricing',
 'Revenue, Finance, and Data Analyst',
 'Public Policy Data Analyst',
 'Lead Data Engineer, Big Data',
 'LEAD COMPUTER SCIENTIST - SR. COMPUTER SCIENTIST - SPACE DATA SYSTEMS',
 'Distinguished Data Scientist',
 'Sr. Research Scientist-Liver',
 'Sr. Data Scientist II',
 'Assistant, Associate, or Full Research Scientist (FY 19-20)',
 'SystemC Modeling Engineer',
 'Senior Data Engineer - Core Data Science & Engineering',
 'Adobe Experience Platform Data Engineer',
 'Biotransformation Scientist and DMPK Design Lead',
 '(Senior) Data Engineer',
 'Data Scientist / Data Engineer',
 'Scientist - Biomarker and Flow Cytometry',
 'Data Engineer _ Chicago, IL || 06+ Months Contract',
 'Business Intelligence Analyst, Pharmacy Analytics, Full Time Days',
 'Senior Scientist - CMC Analytical Development',
 'NLP Data Scientist',
 'Aquatic Scientist',
 'Scientist, CAR-T Analytical Development-Cell & Gene Therapy, Vaccines',
 'Master Data Engineer',
 'HCC Data Analyst',
 'Principal Data Engineer',
 'Medical Lab Tech / Medical Lab Scientist - Lab - Mercy Sylvania - Full Time Nights',
 'Signal and Information Processing Research Scientist',
 'Sr Health Data Scientist - Precision Care - REMOTE',
 'Jr. Business Intelligence Analyst',
 'Senior Scientist, Assay Operations',
 'Research Scientist - Data Science (Earth & Atmospheric Sciences)',
 'Sr. Consultant Data Engineer',
 'Search Data Scientist, Apple Media Products',
 'Data Scientist / Analytics, Data Engineering',
 'Administrative Assistant / Data Analyst Supporting the DEA #20-318',
 'Data Analyst 1',
 'Data Analyst - Lansing, MI',
 'Scientist II, DMPK (Biotransformation)',
 'Data Engineer-Houston,TX',
 'Lead Business Intelligence Analyst',
 'Data Science Consultant - Supply Chain',
 'Business Intelligence Analyst Tableau From Scratch & Performance Bonuses',
 'Card Data Analyst',
 'Senior Data Scientist - Ads Optimization',
 'Data Modeler Consultant',
 'Principal Marketing Scientist',
 '#NAME?',
 'Data Scientist, Applied Machine Learning - Bay',
 'Data Scientist Boston',
 'Virology Data Analysts',
 'Sr. Data Engineer with Strong Python',
 'Medical Laboratory Scientist - Pathology/Blood Bank - Night shift',
 'Data Engineer- Internal Integration',
 'Performance Data Analyst',
 'Scientist, Analytical Outsource Stability',
 'Medical Lab Scientist, Lab Services - CLC Laboratory (up to 19 hours per week; evenings & weekends)',
 'Scientist, Residual DNA Testing',
 'Data Scientist - Social Impact (FT)',
 'Associate Scientist / Senior Research Associate, Cancer Immunotherapy',
 'Fleet Optimization Data Analyst (Solar + Storage)',
 'Data Engineer *',
 'Sr. Tech Svc Scientist (I)',
 'Remote work - Data Scientist with background in Epidemiology',
 'Data Scientist II - Cell & Gene Therapy',
 'Principal Scientist 3',
 'HT Downstream Sr Scientist',
 'Business Analyst / Data Analyst',
 'Data Scientist Lead, Capacity Planning & Analytics',
 'ANALYST - SCIENTIST - KINETICS',
 'Applied Mathematics and Computational Research Scientist',
 'Senior Manager, Data Scientist - Pediatric Nutrition - Columbus, OH',
 'Senior Scientist, Computational Biology',
 'Polymer Modified Asphalt Engineer/Scientist',
 'Fleet Coordinator (Data Analyst)',
 'Lead Data Scientist',
 'Principal Data Scientist II (Statistical Modeling)',
 'Data Analyst, Finance (H)',
 'Data Scientist for Corporate Finance',
 'Data Analyst Mid or Senior',
 'Data Analytics Consultant (TS/SCI/polygraph)',
 'Digital Signal Processing Scientist',
 'Data Science Support Analyst (Journeyman)',
 'Data Scientist for Industrial Image Processing - Columbus, OH',
 'Graduate - Data Science for Ocean of Things (DARPA)',
 'AI/ML - Siri Data Engineer, Siri Search & Knowledge Platform',
 'Sr. Data Science Architect',
 'Associate Director, Data Partner, Global Biometrics and Data Science',
 'Senior SW Engineer, Data Science ( Kubernetes/ Docker ) Remote USA',
 'Sr. Scientist, Clinical Development',
 'Remote -Data Engineer',
 'Jr. Data Analyst',
 'Entry Level Data Scientist',
 'Applied Scientist',
 'Data Architect - Azure',
 'Quantitative Researcher, Market Simulator',
 'CSI Data Analyst',
 'Machine Learning Scientist I',
 'Senior Data Modeler - Technical Architect',
 'Mesa Data Science Tutor Jobs',
 'Associate Scientist - Sensory - Jr (Daily/Weekly OT)',
 'Data Integration Architect',
 'Bioinformatics Scientist, Data Operations',
 'Data Engineer (Mid-Level)',
 'Sr. Scientist Analytical Method Development',
 'Lead Consultant - Analytics Consulting',
 'Data Scientist - Risk',
 'Data Engineer II',
 'Data Scientist/Data Science Instructor (Part-time)',
 'Scientist, Sequencing',
 'Data Scientist, Research & Development',
 'Principal Scientist, Computational Genomics',
 'Marketing Data Analyst',
 'Data Scientist needed - 10 positions',
 'Data Engineer, Apple Media Products',
 'Data Analyst or Sr. Data Analyst, Operations Analytics',
 'Senior Data Scientist (Remote)',
 'Remote Sensing Data Scientist',
 'Data Scientist, Game Analytics',
 'Soil Scientist (Direct Hire)',
 'Senior Scientist - Molecular Biology',
 'Sr. Data Visualization Developer',
 'Data Engineer 4- Guidewire Data Hub',
 'Medical Laboratory Scientist Medical Technologist 2',
 'Product Development Scientist - Covid 19',
 'Associate Scientist R&D',
 'Senior Data Science Engineer',
 'Exploratory Data Analysis Instructor',
 'Analytics Consultant 5',
 'MTSG Scientist I',
 'Protein Scientist',
 'Senior Marketing Data Analyst',
 'Manager, Data Science',
 'Workday Data Consultant',
 'Information Security Data Analyst',
 'Machine Learning Engineer/Scientist',
 'Data Analyst - Marketing',
 'Quantitative Research Associate',
 'Scottsdale Data Science Tutor Jobs',
 'Medical Laboratory Scientist Micro Lab Days',
 'Sr. Big data Ebgineer',
 'Data Analyst Assistant',
 'Data Analyst BI Engineer',
 'Data Analyst – Global Quality Team',
 'Data Scientist/Programmer, Sr. Analyst - Abbott Nutrition - Columbus, OH',
 'Electro-Optical/Infared Senior Research Scientist, OPIR',
 'Principal Scientist, HEOR',
 'Business Intelligence Analyst I/II',
 'Data Scientist, Customer Intelligence - Opportunity for Working Remotely Jacksonville, FL',
 'Scientist IV, Occupational Toxicologist',
 'Billingual Chinese - Data Analyst',
 'Data Scientist (Java)',
 'Senior Machine Learning Engineer',
 'Machine Learning & Data Engineer (Remote)',
 'Instructional Aide (TEMP) - Masters of Applied Data Science Spring / Summer 2021',
 'Junior Data Analyst',
 'Practice Area Lead - Machine Learning - Data & Analytics',
 'Project Scientist II',
 'Scientist I/II',
 'Data Scientist, Strategic Research and Analytics',
 'Solar Data Analyst',
 'Big Data Administrator/Developer',
 'Data Scientist (Analytics)',
 'Informatica Data Modeler',
 'Senior Data Analyst, Marketing',
 'Connected Vehicle Data Scientist',
 'Consultant, Advanced Data Analytics & Insights – Digital Analytics',
 'Senior Data Scientist (Commercial Analytics)',
 'Data Scientist, Marketplace Economics',
 'Principal Scientist, PK Sciences Oncology',
 'Medical Lab Scientist - Molecular',
 'Performance Improvement Data Analyst',
 'Research Scientist 1, PK and ADA Bioanalytical Development and Validation 1',
 'Azure Data Engineer',
 'Digital Analytics Manager',
 'Principal Scientist, Global Self-Care Stability',
 'Senior Software/Data Engineer',
 'Sr Associate Scientist, Phage Display, Molecular Biology',
 'AI/ML - Sr Data Scientist, Siri Product Strategy',
 'Senior SW Engineer, Data Science',
 'Data Analyst (Asset Management / eDiscovery)',
 'Sr. Data Engineer (Remote US)',
 'Senior Data Analyst - Product Analytics (open to remote)',
 'Business Applications, Infor Analytics Consultant',
 'Senior SAS Programmer (Scientist)',
 'Senior Scientist-UV Coatings',
 'Senior Associate, Data Scientist, Intelligent Forecasting',
 'QC Associate Scientist',
 'Recruiting Manager, Data Science',
 'Attribute Data Analyst - NON TECHNICAL',
 'Data Scientist, Applied Machine Learning - Bay Area',
 'Research Scientist - Biopharm cGMP Reports, and Regulatory Documentation',
 'Sr Health Data Scientist - REMOTE',
 'XYZ Data Analyst',
 'Data Scientists in Biomedical Data Science - Schmidt Data X Project',
 'Senior Data Analyst, Sales',
 'Data Scientist 3 (Tableau - Statistics (Fleet Readiness), Tableau - Statistics (IT Portfolio), Predi',
 'Data Engineer',
 'Research Scientist Assistant I/II',
 'Senior Quantitative Researcher',
 'Data Modeler (Data Vault)',
 'Scientist, Data',
 'Quantitative Researcher – PhD Hire',
 'Corporate Senior Business Intelligence Analyst',
 'Data Analyst, Lead',
 'Senior Associate Scientist, Parallel Medicinal Chemistry - Discovery Chemistry - La Jolla',
 'Data Scientist - Altdata',
 'Data Analytics Manager - Global Business Services',
 'Data Scientist – Network Analysis and Control',
 'Data Scientist Sr. - Conversation Designer & NLP Analyst',
 'Data Analyst, Tax (Affordable Care Act) (ACA) (Manager) (Multiple Positions)',
 'Cyber Security Senior Research Scientist',
 'Full Stack Data Scientist Intern - Fall 2020 / Spring',
 'Cyber Security Data Engineer',
 'Business and Customer Data Analyst',
 'Automotive eCommerce Data Analyst',
 'Field Application Scientist - Mid-Atlantic',
 'Senior Research Scientist I, Data Analytics',
 'Quantitative Researcher – Full Time (US)',
 'Senior Scientist, CAR-T Analytical Development-Cell & Gene Therapy, Vaccines (PCR)',
 'Director, Network Optimization & Data Sciences',
 'Research Scientist - Immunology Research',
 'Senior Scientist, Immunology',

In [56]:
len(set(df['Job Title']))

2552

In [57]:
df.to_csv('myDataFrame2.csv')